config/routes.rb
Rails.application.routes.draw do
  root 'net_points#index'
  resources :net_points do
    collection do
      get 'netmap'
      get 'heatmap'
      get 'randomizer'
      get 'direction'
    end
  end

  resources :operators
  devise_for :users
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/net_point.rb
class NetPoint < ApplicationRecord
  belongs_to :operator
  belongs_to :user
end

app/models/operator.rb
class Operator < ApplicationRecord
    has_many :net_points
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :net_points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/net_points_controller.rb
class NetPointsController < ApplicationController
  before_action :set_net_point, only: [:show, :edit, :update, :destroy]

  # GET /net_points
  # GET /net_points.json
  def index
    @net_points = NetPoint.all
  end

  # GET /net_points/1
  # GET /net_points/1.json
  def show
  end

  def netmap
  #  render layout: 'netmap'
    @net_points = NetPoint.all
    @markers = []
    @net_points.each do |net_point|
      @markers.push(
      [net_point.latitude, net_point.longitude, net_point.dbm]
      )
    end
  end

  def randomizer
    @net_points = NetPoint.all
    @point = NetPoint.last
    @id = @point.id
      @net_points.each do |net_point|
      @dbm = rand(-110...-75)
      net_type = ['2G', '3G', '4G']
      @lte = net_type[rand(net_type.size)]
      @id += 1
      operators = [[2, 2], [7, 20]]
      @operator_id = operators[rand(operators.size)] 

    signals = NetPoint.create(id: @id, latitude: net_point.latitude, longitude: net_point.longitude, dbm: @dbm, asu: net_point.asu, mcc: net_point.mcc, operator_id: @operator_id[0], mnc: @operator_id[1], net_type: @lte, user_id: 1 )  
    end
    redirect_to root_path
  end

  def heatmap
    @net_points = NetPoint.all
    @markers = []
    @net_points.each do |net_point|
      @markers.push(
        [net_point.latitude, net_point.longitude, net_point.dbm + 110]
      )
    end
  
  end

  def direction
    @net_points = NetPoint.all
    @markers = []
    @net_points.each do |net_point|
      @markers.push(
        [net_point.latitude, net_point.longitude, net_point.dbm + 110]
      )
    end
  end

  # GET /net_points/new
  def new
    @net_point = NetPoint.new
  end

  # GET /net_points/1/edit
  def edit
  end

  # POST /net_points
  # POST /net_points.json
  def create
    @net_point = NetPoint.new(net_point_params)

    respond_to do |format|
      if @net_point.save
        format.html { redirect_to @net_point, notice: 'Net point was successfully created.' }
        format.json { render :show, status: :created, location: @net_point }
      else
        format.html { render :new }
        format.json { render json: @net_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /net_points/1
  # PATCH/PUT /net_points/1.json
  def update
    respond_to do |format|
      if @net_point.update(net_point_params)
        format.html { redirect_to @net_point, notice: 'Net point was successfully updated.' }
        format.json { render :show, status: :ok, location: @net_point }
      else
        format.html { render :edit }
        format.json { render json: @net_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /net_points/1
  # DELETE /net_points/1.json
  def destroy
    @net_point.destroy
    respond_to do |format|
      format.html { redirect_to net_points_url, notice: 'Net point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_net_point
      @net_point = NetPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def net_point_params
      params.require(:net_point).permit(:latitude, :longitude, :dbm, :asu, :mcc, :operator_id, :mnc, :net_type, :user_id)
    end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :set_operator, only: [:show, :edit, :update, :destroy]

  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.all
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
  end

  # GET /operators/new
  def new
    @operator = Operator.new
  end

  # GET /operators/1/edit
  def edit
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to operators_path, notice: 'Operator was successfully created.' }
        format.json { render :show, status: :created, location: @operator }
      else
        format.html { render :new }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operators/1
  # PATCH/PUT /operators/1.json
  def update
    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { render :show, status: :ok, location: @operator }
      else
        format.html { render :edit }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator.destroy
    respond_to do |format|
      format.html { redirect_to operators_url, notice: 'Operator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operator
      @operator = Operator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operator_params
      params.require(:operator).permit(:mnc, :name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/net_points_helper.rb
module NetPointsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= nav_bar brand: image_tag("logo_new.svg", height: '28'), brand_link: root_path  %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/netmap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hackathon" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Hackathon</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/net_points/_form.html.erb
<%= form_for @net_point, :html => { :class => "form-horizontal net_point" } do |f| %>

  <% if @net_point.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@net_point.errors.count, "error") %> prohibited this net_point from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @net_point.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :latitude, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :latitude, :class => 'form-control' %>
    </div>
    <%=f.error_span(:latitude) %>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :longitude, :class => 'form-control' %>
    </div>
    <%=f.error_span(:longitude) %>
  </div>
  <div class="form-group">
    <%= f.label :dbm, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :dbm, :class => 'form-control' %>
    </div>
    <%=f.error_span(:dbm) %>
  </div>
  <div class="form-group">
    <%= f.label :asu, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :asu, :class => 'form-control' %>
    </div>
    <%=f.error_span(:asu) %>
  </div>
  <div class="form-group">
    <%= f.label :mcc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mcc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mcc) %>
  </div>
  <div class="form-group">
    <%= f.label :operator_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :operator_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:operator_id) %>
  </div>
  <div class="form-group">
    <%= f.label :mnc, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :mnc, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mnc) %>
  </div>
  <div class="form-group">
    <%= f.label :net_type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :net_type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:net_type) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                net_points_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/net_points/direction.html.erb
<div id="floating-panel">
    <b>Откуда: </b>
    <select id="start">
      <option value="казань">Казань</option>
      <option value="аэропорт, казань">Аэропорт Казань</option>
      <option value="железнодорожный вокзал, казань">Железнодорожный вокзал, Казань</option>
      <option value="нижний новгород">Нижний Новгород</option>
      <option value="москва">Москва</option>
      <option value="красноярск">Красноярск</option>
      <option value="петербург">Санкт Петербург</option>
      <option value="хабаровск">Хабаровск</option>
      <option value="красноярск">Красноярск</option>
      <option value="абакан">Абакан</option>
      <option value="иркутск">Иркутск</option>
      <option value="новосибирск">Новосибирск</option>
    </select>
    <b>Куда: </b>
    <select id="end">
    <option value="казань">Казань</option>
    <option value="аэропорт, казань">Аэропорт Казань</option>
    <option value="набережные"+"челны">Набережные Челны</option>
    <option value="нижний новгород">Нижний Новгород</option>
    <option value="москва">Москва</option>
    <option value="красноярск">Красноярск</option>
    <option value="петербург">Санкт Петербург</option>
    <option value="хабаровск">Хабаровск</option>
    <option value="красноярск">Красноярск</option>
    <option value="абакан">Абакан</option>
    <option value="иркутск">Иркутск</option>
    <option value="новосибирск">Новосибирск</option>
    </select>
    </div>
    <div id="map"></div>
    <script>
    var markers = [];
    var heatmapData = [];
    markers = <%= @markers %>;

    for (var i = 0; i < markers.length; i++) {
      var marker = markers[i];
      heatmapData.push({location: new google.maps.LatLng(marker[0], marker[1]), weight: marker[2], title: "Уровень сигнала " + marker[2] + "dBm"}) 

    }

      function initMap() {
        var Kazan = {lat: 55.611587, lng: 49.2968417};
        var directionsService = new google.maps.DirectionsService();
        var directionsRenderer = new google.maps.DirectionsRenderer();
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 7,
          center: Kazan
        });
        directionsRenderer.setMap(map);

        var onChangeHandler = function() {
          calculateAndDisplayRoute(directionsService, directionsRenderer);
        };
        document.getElementById('start').addEventListener('change', onChangeHandler);
        document.getElementById('end').addEventListener('change', onChangeHandler);
      }

      function calculateAndDisplayRoute(directionsService, directionsRenderer) {
        directionsService.route(
            {
              origin: {query: document.getElementById('start').value},
              destination: {query: document.getElementById('end').value},
              travelMode: 'TRANSIT'
            },
            function(response, status) {
              if (status === 'OK') {
                directionsRenderer.setDirections(response);
              } else {
                window.alert('Directions request failed due to ' + status);
              }
            });
      }
      var heatmap = new google.maps.visualization.HeatmapLayer({
        data: heatmapData
       //data: markers
      });
      heatmap.setMap(map);

    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap&libraries=visualization">
    </script>

app/views/net_points/edit.html.erb
<%- model_class = NetPoint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/net_points/heatmap.html.erb
<script type="text/javascript"
src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&libraries=visualization">
</script>

<div id="map"></div>
    <script>
      var map;
      var markers = [];
      var heatmapData = [];
      markers = <%= @markers %>;

      for (var i = 0; i < markers.length; i++) {
        var marker = markers[i];
        heatmapData.push({location: new google.maps.LatLng(marker[0], marker[1]), weight: marker[2], title: "Уровень сигнала " + marker[2] + "dBm"}) 

      }

      
      var Kazan = new google.maps.LatLng(55.611587, 49.2968417);
      
      map = new google.maps.Map(document.getElementById('map'), {
        center: Kazan,
        zoom: 13,
        //mapTypeId: 'satellite'
      });
      
      var heatmap = new google.maps.visualization.HeatmapLayer({
        data: heatmapData
       //data: markers
      });
      heatmap.setMap(map);

    </script>
    

app/views/net_points/index.html.erb
<%- model_class = NetPoint -%>
<div class="page-header">
 <!-- <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1> -->
 <h2> Результаты измерений: точки покрытия сети мобильной связи. </h2>
 <!-- <%= button_to "MTC", net_points_path(@net_point, operator_id: 1) %>  -->
</div>
<table class="table table-striped">
  <thead>
    <tr>
    <!--  <th><%= model_class.human_attribute_name(:id) %></th>  -->
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:dbm) %></th>
    <!--  <th><%= model_class.human_attribute_name(:asu).upcase %></th> -->
      <th><%= model_class.human_attribute_name(:mcc).upcase %></th>
      <th><%= model_class.human_attribute_name(:operator_id) %></th>
    <!--   <th><%= model_class.human_attribute_name(:mnc).upcase %></th>  -->
      <th><%= model_class.human_attribute_name(:net_type) %></th>
    <!--  <th><%= model_class.human_attribute_name(:user_id) %></th>  -->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @net_points.each do |net_point| %>
      <tr>
      <!--  <td><%= link_to net_point.id, net_point_path(net_point) %></td>  -->
        <td><%= net_point.latitude %></td>
        <td><%= net_point.longitude %></td>
        <td><%= net_point.dbm %></td>
      <!--  <td><%= net_point.asu %></td>  -->
        <td><%= net_point.mcc %></td>
        <td><%= net_point.operator.name %></td> 
      <!--  <td><%= net_point.mnc %></td>  -->
        <td><%= net_point.net_type %></td>
      <!--  <td><%= net_point.user_id %></td>  -->
        <td><%=l net_point.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_net_point_path(net_point), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      net_point_path(net_point),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_net_point_path,
            :class => 'btn btn-primary' %>

app/views/operators/index.html.erb
<%- model_class = Operator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
    <!--  <th><%= model_class.human_attribute_name(:id) %></th>  -->
      <th><%= model_class.human_attribute_name(:mnc).upcase %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
    <!--  <th><%= model_class.human_attribute_name(:created_at) %></th> -->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @operators.each do |operator| %>
      <tr>
     <!--   <td><%= link_to operator.id, operator_path(operator) %></td> -->
        <td><%= operator.mnc %></td>
        <td><%= operator.name %></td>
      <!--  <td><%=l operator.created_at %></td>  -->
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_operator_path(operator), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      operator_path(operator),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_operator_path,
            :class => 'btn btn-primary' %>

app/views/user/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <!--
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      -->
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <!--
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        -->
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>